import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sections/navbar/default";
import FooterSection from "@/components/sections/footer/default";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">

        {/* 🔥 FIXED NAVBAR WITHOUT LINE */}
        <header className="fixed top-0 left-0 w-full z-[999] bg-transparent backdrop-blur-none shadow-none border-none">
          <Navbar className="max-w-7xl mx-auto px-6" />
        </header>

        <main className="pt-20">
          {children}
        </main>

        <FooterSection />
      </body>
    </html>
  );
}
